import { themes as prismThemes } from "prism-react-renderer";
import type { Config } from "@docusaurus/types";
import type * as Preset from "@docusaurus/preset-classic";


// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
const config: Config = {
	title: "QAROS Docs",
	tagline: "Don’t Rewrite. Extend.",
	favicon: "img/favicon.ico",

	// Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
	future: {
		v4: true, // Improve compatibility with the upcoming Docusaurus v4
	},

	// Set the production url of your site here
	url: "https://docs.quaternar.com",
	// Set the /<baseUrl>/ pathname under which your site is served
	// For GitHub pages deployment, it is often '/<projectName>/'
	baseUrl: "/",

	// GitHub pages deployment config.
	// If you aren't using GitHub pages, you don't need these.
	organizationName: "Quaternar", // Usually your GitHub org/user name.
	projectName: "qaros", // Usually your repo name.

	onBrokenLinks: "throw",
	trailingSlash: true,

	// Even if you don't use internationalization, you can use this field to set
	// useful metadata like html lang. For example, if your site is Chinese, you
	// may want to replace "en" with "zh-Hans".
	i18n: {
		defaultLocale: "en",
		locales: ["en"],
	},

	presets: [
		[
			"classic",
			{
				docs: {
					sidebarPath: "./sidebars.ts",
					editUrl:
						"https://github.com/Quaternar/qaros/tree/main/docs/website/",
				},
				// blog: {
				// 	showReadingTime: true,
				// 	feedOptions: {
				// 		type: ["rss", "atom"],
				// 		xslt: true,
				// 	},
				// 	// Please change this to your repo.
				// 	// Remove this to remove the "edit this page" links.
				// 	editUrl:
				// 		"https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/",
				// 	// Useful options to enforce blogging best practices
				// 	onInlineTags: "warn",
				// 	onInlineAuthors: "warn",
				// 	onUntruncatedBlogPosts: "warn",
				// },
				theme: {
					customCss: [
						"./src/css/custom-doxygen2docusaurus.css",
						"./src/css/custom.css",
					],
				},
			} satisfies Preset.Options,
		],
	],

	// Mount additional documentation sources (Doxygen -> Docusaurus Markdown)
	plugins: [
		[
			"@docusaurus/plugin-content-docs",
			{
				id: "api",
				// Generated by doxygen + doxygen2docusaurus
				path: "api",
				routeBasePath: "api/",
				sidebarPath: "./sidebar_api.ts",
			},
		],
		// Keep bookmarks and external links working after the three-guide
		// restructure moved several pages between guides. `onBrokenLinks: "throw"`
		// guards internal links; these client-side redirects cover the published
		// URLs that changed. Keep trailing slashes (`trailingSlash: true`).
		[
			"@docusaurus/plugin-client-redirects",
			{
				redirects: [
					{ from: "/docs/user-guide/coordinate-systems", to: "/docs/developer-guide/coordinate-systems" },
					{ from: "/docs/user-guide/security-and-onboarding", to: "/docs/operator-guide/security-model" },
					{ from: "/docs/user-guide/the-mixer", to: "/docs/operator-guide/the-mixer" },
					{ from: "/docs/user-guide/using-the-hub", to: "/docs/operator-guide/running-the-hub" },
					{ from: "/docs/user-guide/deployment-and-installation", to: "/docs/operator-guide/installation" },
					{ from: "/docs/user-guide/glossary", to: "/docs/glossary" },
					{ from: "/docs/developer-guide/examples/c/dynamic-loading", to: "/docs/developer-guide/tutorials/c/dynamic-loading" },
					{ from: "/docs/developer-guide/examples/c/onboarding-and-rejoin", to: "/docs/developer-guide/tutorials/c/onboarding-and-rejoin" },
					{ from: "/docs/developer-guide/examples/c/gui-panel-operations", to: "/docs/developer-guide/tutorials/c/gui-panel-operations" },
					{ from: "/docs/developer-guide/examples/c/app-volume-management", to: "/docs/developer-guide/tutorials/c/app-volume-management" },
					{ from: "/docs/developer-guide/examples/c/cpu-rendering", to: "/docs/developer-guide/tutorials/c/cpu-rendering" },
				],
			},
		],
	],

	// Theme-aware favicon: the cube mark has a black wireframe on light tab
	// strips and a white wireframe on dark ones. The favicon.ico above stays as
	// the universal fallback (bookmarks, older browsers, RSS). These PNGs are
	// generated once from the logo and committed under static/img — not on build.
	headTags: [
		{
			tagName: "link",
			attributes: {
				rel: "icon",
				type: "image/png",
				href: "/img/favicon-light.png",
				media: "(prefers-color-scheme: light)",
			},
		},
		{
			tagName: "link",
			attributes: {
				rel: "icon",
				type: "image/png",
				href: "/img/favicon-dark.png",
				media: "(prefers-color-scheme: dark)",
			},
		},
	],

	themeConfig: {
		colorMode: {
			respectPrefersColorScheme: true
		},
		// Social share card (Open Graph / Twitter)
		image: "img/social-card.jpg",
		navbar: {
			logo: {
				alt: "Quaternar Logo",
				src: "img/quaternar-logo.png",
				srcDark: "img/quaternar-logo-dark.png",
			},
			items: [
				{
					type: "docSidebar",
					sidebarId: "userSidebar",
					position: "left",
					label: "User Guide",
				},
				{
					type: "docSidebar",
					sidebarId: "developerSidebar",
					position: "left",
					label: "Developer Guide",
				},
				{
					type: "docSidebar",
					sidebarId: "operatorSidebar",
					position: "left",
					label: "Admin & Operator",
				},
				{
					type: "dropdown",
					label: "C API",
					to: "/api/qar-streaming-c/",
					position: "left",
					items: [
						{
							label: "C API",
							to: "/api/qar-streaming-c/groups/qar-c-api/"
						},
						{
							label: "Tutorials",
							to: "/docs/developer-guide/tutorials/c/dynamic-loading/"
						},
						{
							label: "Files",
							to: "/api/qar-streaming-c/files/"
						}
					]
				},
				{
					to: "/docs/glossary",
					label: "Glossary",
					position: "right",
				},
				{
					href: "https://github.com/quaternar/qaros",
					label: "GitHub",
					position: "right",
				},
			],
		},
		footer: {
			style: "dark",
			links: [
				{
					title: "Docs",
					items: [
						{
							label: "Knowledge Base",
							to: "/docs/intro",
						},
					],
				},
				{
					title: "Company",
					items: [
						{
							label: "Website",
							href: "https://quaternar.com",
						},
						{
							label: "Contact",
							href: "https://quaternar.com/#contact-us",
						},
					],
				},
				{
					title: "Social",
					items: [
						{
							label: "LinkedIn",
							href: "https://www.linkedin.com/company/quaternar/",
						},
						{
							label: "YouTube",
							href: "https://www.youtube.com/@QuaternAR",
						},
					],
				},
			],
			copyright: `© ${new Date().getFullYear()} Quaternar a.s. All rights reserved.`,
		},
		prism: {
			theme: prismThemes.github,
			darkTheme: prismThemes.dracula,
		},
	} satisfies Preset.ThemeConfig,
	markdown: {
		format: "detect",
	},
};

export default config;
