import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * One sidebar per guide. Each is autogenerated from a single subfolder so the
 * left navigation only ever shows the guide you are currently in.
 *
 * Ordering inside each guide comes from the `sidebar_position` frontmatter of
 * its pages (kept contiguous per folder).
 *
 * `intro.md` and `glossary.md` deliberately live at the top level of `docs/`
 * and belong to NO sidebar: `intro` is the landing hub and `glossary` is a
 * shared reference reached from the navbar. Because each sidebar below is
 * scoped to a subfolder `dirName`, the autogenerator never picks them up, so
 * they render full-width.
 */
const sidebars: SidebarsConfig = {
  userSidebar: [{ type: 'autogenerated', dirName: 'user-guide' }],
  developerSidebar: [{ type: 'autogenerated', dirName: 'developer-guide' }],
  operatorSidebar: [{ type: 'autogenerated', dirName: 'operator-guide' }],
};

export default sidebars;
